import type { AppManifest } from '../types/appManifest';

/**
 * Pre-built app catalog for the Nebula OS App Store.
 * All apps are "html" type with fully functional inline code.
 */
export const appCatalog: AppManifest[] = [
  {
    id: 'store-calculator',
    name: 'Calculator',
    icon: '🧮',
    description: 'A sleek calculator with basic math operations.',
    type: 'html',
    html: `<!DOCTYPE html><html><head><style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:system-ui;background:#1a1a2e;color:#e2e8f0;display:flex;align-items:center;justify-content:center;height:100vh}.calc{width:280px;background:#16213e;border-radius:16px;padding:20px;box-shadow:0 8px 32px rgba(0,0,0,.4)}.display{background:#0f3460;border-radius:8px;padding:16px;margin-bottom:16px;text-align:right;font-size:28px;min-height:60px;word-break:break-all;color:#e94560}.buttons{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.btn{border:none;border-radius:8px;padding:16px;font-size:18px;cursor:pointer;transition:all .2s}.btn:hover{transform:scale(1.05)}.num{background:#1a1a2e;color:#e2e8f0}.op{background:#e94560;color:#fff}.eq{background:#0f3460;color:#e94560;grid-column:span 2}.clear{background:#533483;color:#fff}</style></head><body><div class="calc"><div class="display" id="display">0</div><div class="buttons"><button class="btn clear" onclick="clearAll()">C</button><button class="btn op" onclick="append('(')">(</button><button class="btn op" onclick="append(')')">)</button><button class="btn op" onclick="append('/')">÷</button><button class="btn num" onclick="append('7')">7</button><button class="btn num" onclick="append('8')">8</button><button class="btn num" onclick="append('9')">9</button><button class="btn op" onclick="append('*')">×</button><button class="btn num" onclick="append('4')">4</button><button class="btn num" onclick="append('5')">5</button><button class="btn num" onclick="append('6')">6</button><button class="btn op" onclick="append('-')">−</button><button class="btn num" onclick="append('1')">1</button><button class="btn num" onclick="append('2')">2</button><button class="btn num" onclick="append('3')">3</button><button class="btn op" onclick="append('+')">+</button><button class="btn num" onclick="append('0')">0</button><button class="btn num" onclick="append('.')">.</button><button class="btn eq" onclick="calculate()">=</button></div></div><script>let expr='';function append(v){expr+=v;document.getElementById('display').textContent=expr}function clearAll(){expr='';document.getElementById('display').textContent='0'}function calculate(){try{let r=Function('"use strict";return ('+expr+')')();document.getElementById('display').textContent=r;expr=String(r)}catch{document.getElementById('display').textContent='Error';expr=''}}</script></body></html>`,
  },
  {
    id: 'store-clock',
    name: 'Clock',
    icon: '🕐',
    description: 'Analog and digital clock with smooth animation.',
    type: 'html',
    html: `<!DOCTYPE html><html><head><style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:system-ui;background:#0a0a0f;color:#e2e8f0;display:flex;flex-direction:column;align-items:center;justify-content:center;height:100vh;gap:20px}.clock{width:200px;height:200px;border-radius:50%;border:3px solid #8b5cf6;position:relative;box-shadow:0 0 20px rgba(139,92,246,.3)}.hand{position:absolute;bottom:50%;left:50%;transform-origin:bottom center;border-radius:4px}.hour{width:4px;height:50px;background:#e2e8f0;margin-left:-2px}.minute{width:3px;height:70px;background:#8b5cf6;margin-left:-1.5px}.second{width:1px;height:80px;background:#ec4899;margin-left:-.5px}.center{width:10px;height:10px;background:#ec4899;border-radius:50%;position:absolute;top:50%;left:50%;transform:translate(-50%,-50%)}.digital{font-size:36px;font-weight:bold;color:#8b5cf6;text-shadow:0 0 10px rgba(139,92,246,.5)}.date{font-size:14px;opacity:.7}</style></head><body><div class="clock"><div class="hand hour" id="hour"></div><div class="hand minute" id="min"></div><div class="hand second" id="sec"></div><div class="center"></div></div><div class="digital" id="digital"></div><div class="date" id="date"></div><script>function update(){const now=new Date();const h=now.getHours()%12;const m=now.getMinutes();const s=now.getSeconds();document.getElementById('hour').style.transform='rotate('+(h*30+m*.5)+'deg)';document.getElementById('min').style.transform='rotate('+(m*6)+'deg)';document.getElementById('sec').style.transform='rotate('+(s*6)+'deg)';document.getElementById('digital').textContent=now.toLocaleTimeString();document.getElementById('date').textContent=now.toLocaleDateString(undefined,{weekday:'long',year:'numeric',month:'long',day:'numeric'})}setInterval(update,1000);update()</script></body></html>`,
  },
  {
    id: 'store-snake',
    name: 'Snake Game',
    icon: '🐍',
    description: 'Classic snake game. Use arrow keys to play!',
    type: 'html',
    html: `<!DOCTYPE html><html><head><style>*{margin:0;padding:0;box-sizing:border-box}body{background:#0a0a0f;display:flex;flex-direction:column;align-items:center;justify-content:center;height:100vh;font-family:system-ui;color:#e2e8f0}canvas{border:2px solid #8b5cf6;border-radius:4px;box-shadow:0 0 20px rgba(139,92,246,.3)}.score{margin-top:12px;font-size:18px;color:#8b5cf6}.info{margin-top:8px;font-size:12px;opacity:.6}</style></head><body><canvas id="c" width="300" height="300"></canvas><div class="score">Score: <span id="score">0</span></div><div class="info">Arrow keys to move. Click to restart.</div><script>const c=document.getElementById('c'),ctx=c.getContext('2d');const sz=15,w=c.width/sz,h=c.height/sz;let snake,dir,food,score,running;function init(){snake=[{x:10,y:10}];dir={x:1,y:0};food=newFood();score=0;running=true;document.getElementById('score').textContent='0'}function newFood(){let f;do{f={x:Math.floor(Math.random()*w),y:Math.floor(Math.random()*h)}}while(snake.some(s=>s.x===f.x&&s.y===f.y));return f}function draw(){ctx.fillStyle='#0a0a0f';ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle='#8b5cf6';snake.forEach(s=>{ctx.fillRect(s.x*sz,s.y*sz,sz-1,sz-1)});ctx.fillStyle='#ec4899';ctx.fillRect(food.x*sz,food.y*sz,sz-1,sz-1)}function update(){if(!running)return;const head={x:snake[0].x+dir.x,y:snake[0].y+dir.y};if(head.x<0||head.x>=w||head.y<0||head.y>=h||snake.some(s=>s.x===head.x&&s.y===head.y)){running=false;ctx.fillStyle='rgba(0,0,0,.7)';ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle='#ec4899';ctx.font='20px system-ui';ctx.textAlign='center';ctx.fillText('Game Over!',c.width/2,c.height/2);return}snake.unshift(head);if(head.x===food.x&&head.y===food.y){score++;document.getElementById('score').textContent=score;food=newFood()}else{snake.pop()}draw()}document.addEventListener('keydown',e=>{if(e.key==='ArrowUp'&&dir.y!==1)dir={x:0,y:-1};if(e.key==='ArrowDown'&&dir.y!==-1)dir={x:0,y:1};if(e.key==='ArrowLeft'&&dir.x!==1)dir={x:-1,y:0};if(e.key==='ArrowRight'&&dir.x!==-1)dir={x:1,y:0}});c.addEventListener('click',()=>{init();draw()});init();draw();setInterval(update,120)</script></body></html>`,
  },
  {
    id: 'store-paint',
    name: 'Paint',
    icon: '🎨',
    description: 'Simple drawing canvas with color picker and brush sizes.',
    type: 'html',
    html: `<!DOCTYPE html><html><head><style>*{margin:0;padding:0;box-sizing:border-box}body{background:#1a1a2e;font-family:system-ui;display:flex;flex-direction:column;height:100vh}.toolbar{display:flex;align-items:center;gap:8px;padding:8px 12px;background:#16213e;border-bottom:1px solid #333}.toolbar label{color:#e2e8f0;font-size:12px}.toolbar input[type=color]{width:32px;height:32px;border:none;border-radius:4px;cursor:pointer}.toolbar input[type=range]{width:80px}.toolbar button{background:#8b5cf6;color:#fff;border:none;padding:6px 12px;border-radius:4px;cursor:pointer;font-size:12px}.toolbar button:hover{opacity:.8}canvas{flex:1;cursor:crosshair;background:#fff}</style></head><body><div class="toolbar"><label>Color:</label><input type="color" id="color" value="#8b5cf6"><label>Size:</label><input type="range" id="size" min="1" max="30" value="4"><button onclick="clearCanvas()">Clear</button><button onclick="eraser()">Eraser</button></div><canvas id="c"></canvas><script>const c=document.getElementById('c'),ctx=c.getContext('2d');let drawing=false,lastX=0,lastY=0,isEraser=false;function resize(){c.width=c.offsetWidth;c.height=c.offsetHeight;ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height)}window.addEventListener('resize',resize);resize();c.addEventListener('mousedown',e=>{drawing=true;[lastX,lastY]=[e.offsetX,e.offsetY]});c.addEventListener('mousemove',e=>{if(!drawing)return;ctx.beginPath();ctx.moveTo(lastX,lastY);ctx.lineTo(e.offsetX,e.offsetY);ctx.strokeStyle=isEraser?'#fff':document.getElementById('color').value;ctx.lineWidth=document.getElementById('size').value;ctx.lineCap='round';ctx.stroke();[lastX,lastY]=[e.offsetX,e.offsetY]});c.addEventListener('mouseup',()=>drawing=false);c.addEventListener('mouseleave',()=>drawing=false);function clearCanvas(){ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height)}function eraser(){isEraser=!isEraser}</script></body></html>`,
  },
  {
    id: 'store-pomodoro',
    name: 'Pomodoro Timer',
    icon: '🍅',
    description: '25-minute work sessions with 5-minute breaks.',
    type: 'html',
    html: `<!DOCTYPE html><html><head><style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:system-ui;background:#0a0a0f;color:#e2e8f0;display:flex;flex-direction:column;align-items:center;justify-content:center;height:100vh;gap:20px}.timer{font-size:72px;font-weight:bold;color:#8b5cf6;text-shadow:0 0 20px rgba(139,92,246,.4)}.status{font-size:18px;opacity:.8}.buttons{display:flex;gap:12px}.btn{padding:12px 24px;border:none;border-radius:8px;font-size:16px;cursor:pointer;transition:all .2s}.btn:hover{transform:scale(1.05)}.start{background:#8b5cf6;color:#fff}.pause{background:#ec4899;color:#fff}.reset{background:#333;color:#e2e8f0}.progress{width:200px;height:4px;background:#333;border-radius:2px;overflow:hidden}.progress-bar{height:100%;background:#8b5cf6;transition:width .5s}</style></head><body><div class="status" id="status">Work Time</div><div class="timer" id="timer">25:00</div><div class="progress"><div class="progress-bar" id="progress"></div></div><div class="buttons"><button class="btn start" id="startBtn" onclick="toggle()">Start</button><button class="btn reset" onclick="reset()">Reset</button></div><script>let time=25*60,total=25*60,running=false,interval,isWork=true;function display(){const m=Math.floor(time/60).toString().padStart(2,'0');const s=(time%60).toString().padStart(2,'0');document.getElementById('timer').textContent=m+':'+s;document.getElementById('progress').style.width=((total-time)/total*100)+'%'}function toggle(){if(running){clearInterval(interval);running=false;document.getElementById('startBtn').textContent='Resume'}else{running=true;document.getElementById('startBtn').textContent='Pause';interval=setInterval(()=>{time--;if(time<=0){clearInterval(interval);running=false;isWork=!isWork;time=isWork?25*60:5*60;total=time;document.getElementById('status').textContent=isWork?'Work Time':'Break Time';document.getElementById('startBtn').textContent='Start';document.getElementById('timer').style.color=isWork?'#8b5cf6':'#ec4899'}display()},1000)}}function reset(){clearInterval(interval);running=false;isWork=true;time=25*60;total=25*60;document.getElementById('status').textContent='Work Time';document.getElementById('startBtn').textContent='Start';document.getElementById('timer').style.color='#8b5cf6';display()}display()</script></body></html>`,
  },
  {
    id: 'store-colorpicker',
    name: 'Color Picker',
    icon: '🎯',
    description: 'Pick colors and get HEX, RGB, and HSL values.',
    type: 'html',
    html: `<!DOCTYPE html><html><head><style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:system-ui;background:#0a0a0f;color:#e2e8f0;display:flex;flex-direction:column;align-items:center;justify-content:center;height:100vh;gap:20px}.preview{width:150px;height:150px;border-radius:16px;border:3px solid #333;box-shadow:0 8px 32px rgba(0,0,0,.4);transition:background .3s}input[type=color]{width:80px;height:40px;border:none;border-radius:8px;cursor:pointer}.values{display:flex;flex-direction:column;gap:8px;align-items:center}.value{background:#16213e;padding:8px 16px;border-radius:8px;font-family:monospace;font-size:14px;cursor:pointer;transition:all .2s;min-width:200px;text-align:center}.value:hover{background:#1a1a4e;transform:scale(1.02)}.label{font-size:11px;opacity:.5;margin-bottom:2px}.copied{position:fixed;top:20px;background:#8b5cf6;color:#fff;padding:8px 16px;border-radius:8px;font-size:14px;opacity:0;transition:opacity .3s}</style></head><body><div class="copied" id="copied">Copied!</div><div class="preview" id="preview" style="background:#8b5cf6"></div><input type="color" id="picker" value="#8b5cf6" oninput="update(this.value)"><div class="values"><div class="value" onclick="copy(this)"><div class="label">HEX</div><span id="hex">#8B5CF6</span></div><div class="value" onclick="copy(this)"><div class="label">RGB</div><span id="rgb">rgb(139, 92, 246)</span></div><div class="value" onclick="copy(this)"><div class="label">HSL</div><span id="hsl">hsl(263, 90%, 66%)</span></div></div><script>function update(hex){document.getElementById('preview').style.background=hex;document.getElementById('hex').textContent=hex.toUpperCase();const r=parseInt(hex.slice(1,3),16),g=parseInt(hex.slice(3,5),16),b=parseInt(hex.slice(5,7),16);document.getElementById('rgb').textContent='rgb('+r+', '+g+', '+b+')';const[h,s,l]=rgbToHsl(r,g,b);document.getElementById('hsl').textContent='hsl('+h+', '+s+'%, '+l+'%)'}function rgbToHsl(r,g,b){r/=255;g/=255;b/=255;const max=Math.max(r,g,b),min=Math.min(r,g,b);let h,s,l=(max+min)/2;if(max===min){h=s=0}else{const d=max-min;s=l>.5?d/(2-max-min):d/(max+min);switch(max){case r:h=(g-b)/d+(g<b?6:0);break;case g:h=(b-r)/d+2;break;case b:h=(r-g)/d+4;break}h/=6}return[Math.round(h*360),Math.round(s*100),Math.round(l*100)]}function copy(el){navigator.clipboard.writeText(el.querySelector('span').textContent);const c=document.getElementById('copied');c.style.opacity='1';setTimeout(()=>c.style.opacity='0',1500)}</script></body></html>`,
  },
];
